name: cadavre_exquisite
description: Un gioco di scrittura collaborativa a turni, ispirato al cadavre exquis.

version: 1.0.2+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  crypto: ^3.0.7
  google_sign_in: ^7.2.0
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/
